trigger:
- main  # You can change this to trigger the pipeline on a different branch

pool:
  name: 'NEW POOL'   # You can choose 'windows-latest' or 'ubuntu-latest'

variables:
  azureSubscription: 'your-azure-connection-name'  # Name of the Azure service connection
  resourceGroup: 'your-resource-group'
  webAppName: 'your-web-app-name'  # Unique web app name
  location: 'East US'  # Azure region for the web app
  appServicePlan: 'your-app-service-plan'
  appDeploymentScript: 'deploy-your-app-script.sh'  # Path to the deployment script

jobs:
- job: DeployAndCleanup
  displayName: 'Deploy Web App and Cleanup after 1 hour'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Step 1: Create Web App in Azure
        az webapp up --name $(webAppName) --resource-group $(resourceGroup) --plan $(appServicePlan) --location $(location)
        
        # Step 2: Deploy your application
        az webapp deployment source config-zip --resource-group $(resourceGroup) --name $(webAppName) --src $(appDeploymentScript)
        
        # Step 3: Set a timeout for 1 hour (3600 seconds)
        echo "Web App deployed. The app will be deleted in 1 hour."
        sleep 3600  # Wait for 1 hour
        
        # Step 4: Delete the Web App after 1 hour
        az webapp delete --name $(webAppName) --resource-group $(resourceGroup)
        
        echo "Web App deleted after 1 hour."
    displayName: 'Deploy Web App and Delete After 1 Hour'
