trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  name: 'NEW POOL'  # Name of your self-hosted agent pool

variables:
  azureSubscription: 'CICDAzureConnect'  # Azure Service Connection name
  azureResourceGroup: 'CICD'  # Resource Group name
  location: 'EastUS'  # Azure region

jobs:
- job: CreateVM
  displayName: 'Create Azure VM'
  steps:
  - task: UseAzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)  # Azure service connection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        # Log into Azure using the provided service connection
        echo "Logging into Azure..."
        az account set --subscription $(azureSubscription)

        # Create the resource group (if it doesn't already exist)
        az group create --name $(azureResourceGroup) --location $(location)

        # Create the VM
        echo "Creating VM..."
        az vm create \
          --resource-group $(azureResourceGroup) \
          --name MyVM \
          --image UbuntuLTS \
          --admin-username azureuser \
          --admin-password 'YourPassword123!' \
          --size Standard_DS1_v2 \
          --location $(location) \
          --authentication-type password \
          --public-ip-sku Standard

  displayName: 'Create VM on Azure'
